### ISSUE TITLE
Bikes module: issue with images

### ISSUE THREAD

**Issue by platzhersh** [velafrica/velafrica-django#12]
#54 NotImplementedError: This backend doesn't support absolute paths.

https://rollbar.com/velafrica-admin/velafrica-admin/items/54/

**Comment by fim13** [comment]
AWS s3 bucket most be configured wrongly, probably public access to 'bikes/*' isn't granted. It works for me.

**Comment by platzhersh** [comment]
Fixed by setting permissions on AWS S3 correctly.
