### ISSUE TITLE
Import/Export not working

### ISSUE THREAD

**Issue by fim13** [velafrica/velafrica-django#27]
export does not show file type options.
import throughs the following error: 
`AttributeError: module 'tablib.formats._xls' has no attribute 'title'`

(https://rollbar.com/velafrica-admin/velafrica-admin/items/66/)

> There has been a dependency update that broke django-import-export. You just need to force tablib version to 0.14.0.
(https://stackoverflow.com/questions/59752539/django-import-export-multiple-forms)

**Comment by platzhersh** [comment]
django-import-export 2.0.1 should fix this:

https://github.com/django-import-export/django-import-export/blob/master/docs/changelog.rst#201-2020-01-15
