### ISSUE TITLE
WeasyPrint to slow for lots of bikes

### ISSUE THREAD

**Issue by fim13** [velafrica/velafrica-django#37]
39 bikes (with images) triggered a timeout at first try yesterday evening
Today it worked, took a few seconds but it worked.

**Comment by platzhersh** [comment]
An idea would be to just start the pdf creation in a separate thread, storing a reference in a PDFCreationJob object or similar, which would be set to INPROGRESS | DONE | FAILED according to the jobs status.

A link to the pdf job could be returned in a notification to the user.

This would probably only be needed for pdf creation of 1+ bikes.

**Comment by fim13** [comment]
Back to reportlab. 

Weasyprint can render an html template, so styling the printout is way simpler for most web developer. If somebody wants to implement a seperate thread that would be nice, but it is not needed, it is running and possible to add stuff to the print out.
