### ISSUE TITLE
Warehouse PartnerSud

### ISSUE THREAD

**Issue by fim13** [velafrica/velafrica-django#44]
While trying to clean up the database a bit, I found some duplicated organisation which where once used as partner sud and once for a Warehouse. Looking into [stock.models](https://github.com/velafrica/velafrica-django/blob/master/velafrica/stock/models.py), I came across the following:
```python
class Warehouse(models.Model):
    '''
    Only Swiss organisations can have warehouses.
    ...
    '''
    organisation = models.ForeignKey(Organisation, ''' ... ''' limit_choices_to={'partnersud': None})
```

What's the reason for the limitation or why is the a Warehouse for Südpartner anyway? 

Maybe somebody knows more. Just wanted to share this.

**Comment by platzhersh** [comment]
Nur zur Vervollständigung: das wurde wohl mal so defniniert, dass nur Schweizer Verarbeitungspartner Lager besitzen können (in der Applikation).
