### ISSUE TITLE
Rides Feld Bemerkungen zu klein

### ISSUE THREAD

**Issue by velafricaZiviExport** [velafrica/velafrica-django#64]
In den Abschnitten "Auftrag" und "Transport" sollte das Feld Bemerkung je min. 500 Zeichen umfassen dürfen (vielleicht besser noch mehr).

**Comment by velafricaZiviExport** [comment]
Ist wieder zurückgesetzt auf 255 Zeichen. Warum?
LG Mats

**Comment by platzhersh** [comment]
Hey Mats, Hab grad Ferien. Werds mir bei Gelegenheit aber anschauen gegen
Ende Monat.

Lg

Chregi

velafricaZiviExport <notifications@github.com> schrieb am Di., 10. März
2020, 14:29:

**Comment by platzhersh** [comment]
Ist nun korrigiert.
